apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemplo
spec:
  selector:
    matchLabels:
      run: exemplo
  replicas: 1
  template:
    metadata:
      labels:
        name: exemplo
        run: exemplo
    spec:
      containers:
        - name: exemplo-view
          image: nestcloud/nestcloud-kubernetes-example:1.1.2
          ports:
            - containerPort: 3200
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/app/build/config.yaml
              name: volume-config
              subPath: config.yaml
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: nestcloud-kubernetes-example-conf
          name: volume-config
      serviceAccountName: nestcloud-kubernetes-example-account